version: '3.8'

services: 
  app:
    build: ./app
    container_name: delta-test-app
    networks:
      - delta-network
    ports: 
      - '3000:3000'
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Delta
      - MYSQL_DATABASE=Delta
    ports:
      - '3306:3306'
    networks:
      - delta-network

networks:
  delta-network:
    driver: bridge


