version: '3.8'

services: 
  mysqldb:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Delta
      - MYSQL_DATABASE=Delta
    ports:
      - '3306:3306'
    networks:
      - delta-network

networks:
  delta-network:
    driver: bridge


